# Generated by Django 5.2.4 on 2025-07-05 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ieltstest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListeningText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ltitle', models.CharField(max_length=200)),
                ('laudio_file', models.FileField(upload_to='listening_audio/')),
            ],
        ),
        migrations.RemoveField(
            model_name='question',
            name='reading_text',
        ),
        migrations.RenameField(
            model_name='readingtext',
            old_name='image',
            new_name='rimage',
        ),
        migrations.RenameField(
            model_name='readingtext',
            old_name='title',
            new_name='rtitle',
        ),
        migrations.CreateModel(
            name='LQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lquestion_text', models.CharField(max_length=300)),
                ('listening_text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lquestions', to='ieltstest.listeningtext')),
            ],
        ),
        migrations.CreateModel(
            name='LAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lanswer_text', models.CharField(max_length=200)),
                ('is_correct_for_listening', models.BooleanField(default=False)),
                ('lquestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lanswers', to='ieltstest.lquestion')),
            ],
        ),
        migrations.CreateModel(
            name='RQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rquestion_text', models.CharField(max_length=300)),
                ('reading_text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rquestions', to='ieltstest.readingtext')),
            ],
        ),
        migrations.CreateModel(
            name='RAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ranswer_text', models.CharField(max_length=200)),
                ('is_correct_for_reading', models.BooleanField(default=False)),
                ('rquestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ranswers', to='ieltstest.rquestion')),
            ],
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
